### ISSUE TITLE
Don't show the phishing warning when signing in to the Nightly blog

### ISSUE THREAD

**Issue by linabutler** [mozilla-iam/sso-no-phishing#11]
Hi! The [Firefox Nightly blog](https://blog.nightly.mozilla.org/wp-admin/) uses LDAP for authentication, but not via Auth0 SSO. Any chance we can exclude it so that the add-on doesn't show a phishing warning when signing in? Thanks!

**Comment by kbrosnan** [comment]
I see a similar issue with testrail.stage.mozaws.net.

**Comment by gene1wood** [comment]
I've requested enabling SSO for Firfox nightly blog in [Bug 1619467](https://bugzilla.mozilla.org/show_bug.cgi?id=1619467)

**Comment by gene1wood** [comment]
testrail.stage.mozaws.net sits behind auth0proxy.stage.mozaws.net which has SSO authentication but also prompts for authentication of it's own after the SSO auth has been passed.

[Here's some info on testrail](https://wiki.mozilla.org/TestEngineering/Testrail)

The fix for this is likely to change Testrail so it no longer uses LDAP and instead implement a [lightweight wrapper](http://docs.gurock.com/testrail-integration/auth-custom) using Testrail's custom authentication mechanism which looks at the [`Authentication-Info` HTTP header](https://tools.ietf.org/html/rfc7615) which `auth0proxy.stage.mozaws.net` likely passes on to testrail with the authenticated user's identity.

@kbrosnan if you're a testrail user, you may want to request this change in whatever area that's best done.

**Comment by gene1wood** [comment]
One option in the interim is to whitelist manually in the add-on settings.
