### ISSUE TITLE
After exiting SSO, theme goes from green to white (instead of original)

### ISSUE THREAD

**Issue by squelart** [mozilla-iam/sso-no-phishing#4]
Screenshot of the top-right corner of Firefox, showing before/during/after SSO page.
I'm using the default Firefox theme on Nightly 69.0a1 (2019-06-10) (64-bit), Win10. Add-on 1.1.17.

![sso](https://user-images.githubusercontent.com/8499548/59235524-12ea2180-8c35-11e9-9859-fe59d9a70a3f.PNG)

**Comment by gdestuynder** [comment]
@squelart hi and thanks for your report - is the first windows in private browsing mode and it goes from "private mode theme" to green to "gray/white default"?

**Comment by squelart** [comment]
@gdestuynder No, it's all non-private.
In the Add-ons Manager -> Themes, I only have the "Default" one.
I don't think I've ever done anything to change themes in Windows or in Firefox.

**Comment by gdestuynder** [comment]
@squelart The reason I'm asking is because the first bar in your screenshot looks like a private window (dark purple) while the last is the default theme

I would like to understand better what happens though (I don't have a good guess of why you don't get the expected theme back), do you think we could do a shared zoom session? I'm in pacific timezone - i.e. it could be early in the day or late in the day for me to accommodate the timezone differences. Otherwise, you could show me in Whistler next week if you're going there and have time

Thx!
